services:
  # Backend API service
  - type: web
    name: cornell-boxing-api
    env: node
    buildCommand: npm install && npm run install-server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          name: cornell-boxing-frontend
          type: web
          property: url
      - key: MONGODB_URI
        sync: false # User will need to add this manually in Render dashboard

  # Frontend static site
  - type: web
    name: cornell-boxing-frontend
    env: static
    buildCommand: npm install && npm run build-client
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
